@startuml

class owner {
  name * : string
  from * : date
  to  : date
  age * : integer
  nicknames  : array[] of strings
  gender  : enum
  file1  : string [binary]
  file2  : string [byte]
  shoeSize  : integer
  someDouble  : integer

}
@enduml
